function(c){function f(){}function e(c){function a(d){d.prototype.option||(d.prototype.option=function(d){c.isPlainObject(d)&&(this.options=c.extend(!0,this.options,d))})}function d(d,a){c.fn[d]=function(k){if("string"==typeof k){for(var e=b.call(arguments,1),f=0,q=this.length;q>f;f++){var p=c.data(this[f],d);if(p)if(c.isFunction(p[k])&&"_"!==k.charAt(0)){if(p=p[k].apply(p,e),void 0!==p)return p}else g("no such method '"+k+"' for "+d+" instance");else g("cannot call methods on "+d+" prior to initialization; attempted to call '"+
k+"'")}return this}return this.each(function(){var g=c.data(this,d);g?(g.option(k),g._init()):(g=new a(this,k),c.data(this,d,g))})}}if(c){var g="undefined"==typeof console?f:function(d){console.error(d)};return c.bridget=function(g,b){a(b);d(g,b)},c.bridget}}var b=Array.prototype.slice;"function"==typeof define&&define.amd?define("jquery-bridget/jquery.bridget",["jquery"],e):e("object"==typeof exports?require("jquery"):c.jQuery)}(window);
(function(c){function f(d,g){(e(d,g)?h:b)(d,g)}var e,b,h;"classList"in document.documentElement?(e=function(d,g){return d.classList.contains(g)},b=function(d,g){d.classList.add(g)},h=function(d,g){d.classList.remove(g)}):(e=function(d,g){return(new RegExp("(^|\\s+)"+g+"(\\s+|$)")).test(d.className)},b=function(d,g){e(d,g)||(d.className=d.className+" "+g)},h=function(d,g){d.className=d.className.replace(new RegExp("(^|\\s+)"+g+"(\\s+|$)")," ")});var a={hasClass:e,addClass:b,removeClass:h,toggleClass:f,
has:e,add:b,remove:h,toggle:f};"function"==typeof define&&define.amd?define("classie/classie",a):"object"==typeof exports?module.exports=a:c.classie=a})(window);
(function(){function c(){}function f(d,g){for(var a=d.length;a--;)if(d[a].listener===g)return a;return-1}function e(d){return function(){return this[d].apply(this,arguments)}}var b=c.prototype,h=this,a=h.EventEmitter;b.getListeners=function(d){var g,a,b=this._getEvents();if(d instanceof RegExp)for(a in g={},b)b.hasOwnProperty(a)&&d.test(a)&&(g[a]=b[a]);else g=b[d]||(b[d]=[]);return g};b.flattenListeners=function(d){var a,b=[];for(a=0;a<d.length;a+=1)b.push(d[a].listener);return b};b.getListenersAsObject=
function(d){var a,b=this.getListeners(d);return b instanceof Array&&(a={},a[d]=b),a||b};b.addListener=function(d,a){var b,c=this.getListenersAsObject(d),k="object"==typeof a;for(b in c)c.hasOwnProperty(b)&&-1===f(c[b],a)&&c[b].push(k?a:{listener:a,once:!1});return this};b.on=e("addListener");b.addOnceListener=function(d,a){return this.addListener(d,{listener:a,once:!0})};b.once=e("addOnceListener");b.defineEvent=function(d){return this.getListeners(d),this};b.defineEvents=function(d){for(var a=0;a<
d.length;a+=1)this.defineEvent(d[a]);return this};b.removeListener=function(d,a){var b,c,k=this.getListenersAsObject(d);for(c in k)k.hasOwnProperty(c)&&(b=f(k[c],a),-1!==b&&k[c].splice(b,1));return this};b.off=e("removeListener");b.addListeners=function(d,a){return this.manipulateListeners(!1,d,a)};b.removeListeners=function(a,g){return this.manipulateListeners(!0,a,g)};b.manipulateListeners=function(a,g,b){var c,k,e=a?this.removeListener:this.addListener;a=a?this.removeListeners:this.addListeners;
if("object"!=typeof g||g instanceof RegExp)for(c=b.length;c--;)e.call(this,g,b[c]);else for(c in g)g.hasOwnProperty(c)&&(k=g[c])&&("function"==typeof k?e.call(this,c,k):a.call(this,c,k));return this};b.removeEvent=function(a){var g,b=typeof a,c=this._getEvents();if("string"===b)delete c[a];else if(a instanceof RegExp)for(g in c)c.hasOwnProperty(g)&&a.test(g)&&delete c[g];else delete this._events;return this};b.removeAllListeners=e("removeEvent");b.emitEvent=function(a,g){var b,c,k,e,h=this.getListenersAsObject(a);
for(k in h)if(h.hasOwnProperty(k))for(c=h[k].length;c--;)b=h[k][c],!0===b.once&&this.removeListener(a,b.listener),e=b.listener.apply(this,g||[]),e===this._getOnceReturnValue()&&this.removeListener(a,b.listener);return this};b.trigger=e("emitEvent");b.emit=function(a){var b=Array.prototype.slice.call(arguments,1);return this.emitEvent(a,b)};b.setOnceReturnValue=function(a){return this._onceReturnValue=a,this};b._getOnceReturnValue=function(){return!this.hasOwnProperty("_onceReturnValue")||this._onceReturnValue};
b._getEvents=function(){return this._events||(this._events={})};c.noConflict=function(){return h.EventEmitter=a,c};"function"==typeof define&&define.amd?define("eventEmitter/EventEmitter",[],function(){return c}):"object"==typeof module&&module.exports?module.exports=c:h.EventEmitter=c}).call(this);
(function(c){function f(a){var d=c.event;return d.target=d.target||d.srcElement||a,d}var e=document.documentElement,b=function(){};e.addEventListener?b=function(a,d,b){a.addEventListener(d,b,!1)}:e.attachEvent&&(b=function(a,d,b){a[d+b]=b.handleEvent?function(){var d=f(a);b.handleEvent.call(b,d)}:function(){var d=f(a);b.call(a,d)};a.attachEvent("on"+d,a[d+b])});var h=function(){};e.removeEventListener?h=function(a,d,b){a.removeEventListener(d,b,!1)}:e.detachEvent&&(h=function(a,d,b){a.detachEvent("on"+
d,a[d+b]);try{delete a[d+b]}catch(c){a[d+b]=void 0}});e={bind:b,unbind:h};"function"==typeof define&&define.amd?define("eventie/eventie",e):"object"==typeof exports?module.exports=e:c.eventie=e})(window);
(function(c){function f(c){if(c){if("string"==typeof b[c])return c;c=c.charAt(0).toUpperCase()+c.slice(1);for(var a,d=0,g=e.length;g>d;d++)if(a=e[d]+c,"string"==typeof b[a])return a}}var e=["Webkit","Moz","ms","Ms","O"],b=document.documentElement.style;"function"==typeof define&&define.amd?define("get-style-property/get-style-property",[],function(){return f}):"object"==typeof exports?module.exports=f:c.getStyleProperty=f})(window);
(function(c,f){function e(a){var d=parseFloat(a);return-1===a.indexOf("%")&&!isNaN(d)&&d}function b(){}function h(b){function m(){if(!h){h=!0;var d=c.getComputedStyle;if(l=function(){var b=d?function(a){return d(a,null)}:function(a){return a.currentStyle};return function(d){d=b(d);return d||a("Style returned "+d+". Are you running this code in a hidden iframe on Firefox? See http://bit.ly/getsizebug1"),d}}(),k=b("boxSizing")){var m=document.createElement("div");m.style.width="200px";m.style.padding=
"1px 2px 3px 4px";m.style.borderStyle="solid";m.style.borderWidth="1px 2px 3px 4px";m.style[k]="border-box";var v=document.body||document.documentElement;v.appendChild(m);var x=l(m);f=200===e(x.width);v.removeChild(m)}}}var l,k,f,h=!1;return function(a){if(m(),"string"==typeof a&&(a=document.querySelector(a)),a&&"object"==typeof a&&a.nodeType){var b=l(a);if("none"===b.display){for(var g={width:0,height:0,innerWidth:0,innerHeight:0,outerWidth:0,outerHeight:0},b=0,h=d.length;h>b;b++)g[d[b]]=0;return g}g=
{};g.width=a.offsetWidth;g.height=a.offsetHeight;for(var h=g.isBorderBox=!(!k||!b[k]||"border-box"!==b[k]),n=0,A=d.length;A>n;n++){var y=d[n],r=b[y];var t=a,u=r;if(c.getComputedStyle||-1===u.indexOf("%"))r=u;else var r=t.style,D=r.left,z=t.runtimeStyle,B=z&&z.left,r=(B&&(z.left=t.currentStyle.left),r.left=u,u=r.pixelLeft,r.left=D,B&&(z.left=B),u);t=parseFloat(r);g[y]=isNaN(t)?0:t}a=g.paddingLeft+g.paddingRight;n=g.paddingTop+g.paddingBottom;A=g.marginLeft+g.marginRight;y=g.marginTop+g.marginBottom;
t=g.borderLeftWidth+g.borderRightWidth;u=g.borderTopWidth+g.borderBottomWidth;h=h&&f;r=e(b.width);!1!==r&&(g.width=r+(h?0:a+t));b=e(b.height);return!1!==b&&(g.height=b+(h?0:n+u)),g.innerWidth=g.width-(a+t),g.innerHeight=g.height-(n+u),g.outerWidth=g.width+A,g.outerHeight=g.height+y,g}}}var a="undefined"==typeof console?b:function(a){console.error(a)},d="paddingLeft paddingRight paddingTop paddingBottom marginLeft marginRight marginTop marginBottom borderLeftWidth borderRightWidth borderTopWidth borderBottomWidth".split(" ");
"function"==typeof define&&define.amd?define("get-size/get-size",["get-style-property/get-style-property"],h):"object"==typeof exports?module.exports=h(require("desandro-get-style-property")):c.getSize=h(c.getStyleProperty)})(window);
(function(c){function f(a){"function"==typeof a&&(f.isReady?a():d.push(a))}function e(d){d="readystatechange"===d.type&&"complete"!==a.readyState;f.isReady||d||b()}function b(){f.isReady=!0;for(var a=0,b=d.length;b>a;a++)(0,d[a])()}function h(d){return"complete"===a.readyState?b():(d.bind(a,"DOMContentLoaded",e),d.bind(a,"readystatechange",e),d.bind(c,"load",e)),f}var a=c.document,d=[];f.isReady=!1;"function"==typeof define&&define.amd?define("doc-ready/doc-ready",["eventie/eventie"],h):"object"==
typeof exports?module.exports=h(require("eventie")):c.docReady=h(c.eventie)})(window);
(function(c){function f(d,b){return d[a](b)}function e(a,d){a.parentNode||document.createDocumentFragment().appendChild(a);for(var b=a.parentNode.querySelectorAll(d),c=0,e=b.length;e>c;c++)if(b[c]===a)return!0;return!1}function b(a,d){a.parentNode||document.createDocumentFragment().appendChild(a);return f(a,d)}var h,a=function(){if(c.matches)return"matches";if(c.matchesSelector)return"matchesSelector";for(var a=["webkit","moz","ms","o"],d=0,b=a.length;b>d;d++){var k=a[d]+"MatchesSelector";if(c[k])return k}}();
if(a){var d=document.createElement("div");h=f(d,"div")?f:b}else h=e;"function"==typeof define&&define.amd?define("matches-selector/matches-selector",[],function(){return h}):"object"==typeof exports?module.exports=h:window.matchesSelector=h})(Element.prototype);
(function(c,f){"function"==typeof define&&define.amd?define("fizzy-ui-utils/utils",["doc-ready/doc-ready","matches-selector/matches-selector"],function(e,b){return f(c,e,b)}):"object"==typeof exports?module.exports=f(c,require("doc-ready"),require("desandro-matches-selector")):c.fizzyUIUtils=f(c,c.docReady,c.matchesSelector)})(window,function(c,f,e){var b={extend:function(a,b){for(var c in b)a[c]=b[c];return a},modulo:function(a,b){return(a%b+b)%b}},h=Object.prototype.toString;b.isArray=function(a){return"[object Array]"==
h.call(a)};b.makeArray=function(a){var c=[];if(b.isArray(a))c=a;else if(a&&"number"==typeof a.length)for(var e=0,l=a.length;l>e;e++)c.push(a[e]);else c.push(a);return c};b.indexOf=Array.prototype.indexOf?function(a,b){return a.indexOf(b)}:function(a,b){for(var c=0,e=a.length;e>c;c++)if(a[c]===b)return c;return-1};b.removeFrom=function(a,c){var e=b.indexOf(a,c);-1!=e&&a.splice(e,1)};b.isElement="function"==typeof HTMLElement||"object"==typeof HTMLElement?function(a){return a instanceof HTMLElement}:
function(a){return a&&"object"==typeof a&&1==a.nodeType&&"string"==typeof a.nodeName};b.setText=function(){var a;return function(b,c){a=a||(void 0!==document.documentElement.textContent?"textContent":"innerText");b[a]=c}}();b.getParent=function(a,b){for(;a!=document.body;)if(a=a.parentNode,e(a,b))return a};b.getQueryElement=function(a){return"string"==typeof a?document.querySelector(a):a};b.handleEvent=function(a){var b="on"+a.type;this[b]&&this[b](a)};b.filterFindElements=function(a,c){a=b.makeArray(a);
for(var h=[],l=0,k=a.length;k>l;l++){var f=a[l];if(b.isElement(f))if(c){e(f,c)&&h.push(f);for(var f=f.querySelectorAll(c),n=0,q=f.length;q>n;n++)h.push(f[n])}else h.push(f)}return h};b.debounceMethod=function(a,b,c){var e=a.prototype[b],k=b+"Timeout";a.prototype[b]=function(){var a=this[k];a&&clearTimeout(a);var b=arguments,d=this;this[k]=setTimeout(function(){e.apply(d,b);delete d[k]},c||100)}};b.toDashed=function(a){return a.replace(/(.)([A-Z])/g,function(a,b,c){return b+"-"+c}).toLowerCase()};
var a=c.console;return b.htmlInit=function(d,g){f(function(){for(var e=b.toDashed(g),h=document.querySelectorAll(".js-"+e),e="data-"+e+"-options",k=0,f=h.length;f>k;k++){var n,q=h[k],p=q.getAttribute(e);try{n=p&&JSON.parse(p)}catch(x){a&&a.error("Error parsing "+e+" on "+q.nodeName.toLowerCase()+(q.id?"#"+q.id:"")+": "+x);continue}var p=new d(q,n),v=c.jQuery;v&&v.data(q,g,p)}})},b});
(function(c,f){"function"==typeof define&&define.amd?define("flickity/js/cell",["get-size/get-size"],function(e){return f(c,e)}):"object"==typeof exports?module.exports=f(c,require("get-size")):(c.Flickity=c.Flickity||{},c.Flickity.Cell=f(c,c.getSize))})(window,function(c,f){function e(b,a){this.element=b;this.parent=a;this.create()}var b="attachEvent"in c;return e.prototype.create=function(){this.element.style.position="absolute";b&&this.element.setAttribute("unselectable","on");this.shift=this.x=
0},e.prototype.destroy=function(){this.element.style.position="";this.element.style[this.parent.originSide]=""},e.prototype.getSize=function(){this.size=f(this.element)},e.prototype.setPosition=function(b){this.x=b;this.setDefaultTarget();this.renderPosition(b)},e.prototype.setDefaultTarget=function(){this.target=this.x+this.size["left"==this.parent.originSide?"marginLeft":"marginRight"]+this.size.width*this.parent.cellAlign},e.prototype.renderPosition=function(b){this.element.style[this.parent.originSide]=
this.parent.getPositionValue(b)},e.prototype.wrapShift=function(b){this.shift=b;this.renderPosition(this.x+this.parent.slideableWidth*b)},e.prototype.remove=function(){this.element.parentNode.removeChild(this.element)},e});
(function(c,f){"function"==typeof define&&define.amd?define("flickity/js/animate",["get-style-property/get-style-property","fizzy-ui-utils/utils"],function(e,b){return f(c,e,b)}):"object"==typeof exports?module.exports=f(c,require("desandro-get-style-property"),require("fizzy-ui-utils")):(c.Flickity=c.Flickity||{},c.Flickity.animatePrototype=f(c,c.getStyleProperty,c.fizzyUIUtils))})(window,function(c,f,e){for(var b,h=0,a=["webkit","moz","ms","o"],d=c.requestAnimationFrame,g=c.cancelAnimationFrame,
m=0;m<a.length&&(!d||!g);m++)b=a[m],d=d||c[b+"RequestAnimationFrame"],g=g||c[b+"CancelAnimationFrame"]||c[b+"CancelRequestAnimationFrame"];d&&g||(d=function(a){var b=(new Date).getTime(),d=Math.max(0,16-(b-h)),g=c.setTimeout(function(){a(b+d)},d);return h=b+d,g},g=function(a){c.clearTimeout(a)});b={startAnimation:function(){this.isAnimating||(this.isAnimating=!0,this.restingFrames=0,this.animate())},animate:function(){this.applyDragForce();this.applySelectedAttraction();var a=this.x;if(this.integratePhysics(),
this.positionSlider(),this.settle(a),this.isAnimating){var b=this;d(function(){b.animate()})}}};var l=f("transform"),k=!!f("perspective");return b.positionSlider=function(){var a=this.x;this.options.wrapAround&&1<this.cells.length&&(a=e.modulo(a,this.slideableWidth),a-=this.slideableWidth,this.shiftWrapCells(a));a+=this.cursorPosition;a=this.options.rightToLeft&&l?-a:a;a=this.getPositionValue(a);l?this.slider.style[l]=k&&this.isAnimating?"translate3d("+a+",0,0)":"translateX("+a+")":this.slider.style[this.originSide]=
a},b.positionSliderAtSelected=function(){this.cells.length&&(this.x=-this.cells[this.selectedIndex].target,this.positionSlider())},b.getPositionValue=function(a){return this.options.percentPosition?.01*Math.round(a/this.size.innerWidth*1E4)+"%":Math.round(a)+"px"},b.settle=function(a){this.isPointerDown||Math.round(100*this.x)!=Math.round(100*a)||this.restingFrames++;2<this.restingFrames&&(this.isAnimating=!1,delete this.isFreeScrolling,k&&this.positionSlider(),this.dispatchEvent("settle"))},b.shiftWrapCells=
function(a){this._shiftCells(this.beforeShiftCells,this.cursorPosition+a,-1);this._shiftCells(this.afterShiftCells,this.size.innerWidth-(a+this.slideableWidth+this.cursorPosition),1)},b._shiftCells=function(a,b,c){for(var d=0,g=a.length;g>d;d++){var e=a[d];e.wrapShift(0<b?c:0);b-=e.size.outerWidth}},b._unshiftCells=function(a){if(a&&a.length)for(var b=0,d=a.length;d>b;b++)a[b].wrapShift(0)},b.integratePhysics=function(){this.velocity+=this.accel;this.x+=this.velocity;this.velocity*=this.getFrictionFactor();
this.accel=0},b.applyForce=function(a){this.accel+=a},b.getFrictionFactor=function(){return 1-this.options[this.isFreeScrolling?"freeScrollFriction":"friction"]},b.getRestingPosition=function(){return this.x+this.velocity/(1-this.getFrictionFactor())},b.applyDragForce=function(){this.isPointerDown&&this.applyForce(this.dragX-this.x-this.velocity)},b.applySelectedAttraction=function(){var a=this.cells.length;this.isPointerDown||this.isFreeScrolling||!a||this.applyForce((-1*(this.cells[this.selectedIndex].target+
(this.options.wrapAround&&1<a?this.slideableWidth*Math.floor(this.selectedIndex/a):0))-this.x)*this.options.selectedAttraction)},b});
(function(c,f){if("function"==typeof define&&define.amd)define("flickity/js/flickity","classie/classie eventEmitter/EventEmitter eventie/eventie get-size/get-size fizzy-ui-utils/utils ./cell ./animate".split(" "),function(b,e,a,d,g,m,l){return f(c,b,e,a,d,g,m,l)});else if("object"==typeof exports)module.exports=f(c,require("desandro-classie"),require("wolfy87-eventemitter"),require("eventie"),require("get-size"),require("fizzy-ui-utils"),require("./cell"),require("./animate"));else{var e=c.Flickity;
c.Flickity=f(c,c.classie,c.EventEmitter,c.eventie,c.getSize,c.fizzyUIUtils,e.Cell,e.animatePrototype)}})(window,function(c,f,e,b,h,a,d,g){function m(b,d){for(b=a.makeArray(b);b.length;)d.appendChild(b.shift())}function l(b,d){var c=a.getQueryElement(b);return c?(this.element=c,k&&(this.$element=k(this.element)),this.options=a.extend({},this.constructor.defaults),this.option(d),void this._create()):void(n&&n.error("Bad element for Flickity: "+(c||b)))}var k=c.jQuery,w=c.getComputedStyle,n=c.console,
q=0,p={};l.defaults={accessibility:!0,cellAlign:"center",freeScrollFriction:.075,friction:.28,percentPosition:!0,resize:!0,selectedAttraction:.025,setGallerySize:!0};l.createMethods=[];a.extend(l.prototype,e.prototype);l.prototype._create=function(){var a=this.guid=++q;this.element.flickityGUID=a;p[a]=this;this.accel=this.velocity=this.x=this.restingFrames=this.selectedIndex=0;this.originSide=this.options.rightToLeft?"right":"left";this.viewport=document.createElement("div");this.viewport.className=
"flickity-viewport";l.setUnselectable(this.viewport);this._createSlider();(this.options.resize||this.options.watchCSS)&&(b.bind(c,"resize",this),this.isResizeBound=!0);for(var a=0,d=l.createMethods.length;d>a;a++)this[l.createMethods[a]]();this.options.watchCSS?this.watchCSS():this.activate()};l.prototype.option=function(b){a.extend(this.options,b)};l.prototype.activate=function(){if(!this.isActive){this.isActive=!0;f.add(this.element,"flickity-enabled");this.options.rightToLeft&&f.add(this.element,
"flickity-rtl");this.getSize();var a=this._filterFindCellElements(this.element.children);m(a,this.slider);this.viewport.appendChild(this.slider);this.element.appendChild(this.viewport);this.reloadCells();this.options.accessibility&&(this.element.tabIndex=0,b.bind(this.element,"keydown",this));this.emit("activate");a=this.options.initialIndex;this.select(this.isInitActivated?this.selectedIndex:void 0!==a&&this.cells[a]?a:0,!1,!0);this.isInitActivated=!0}};l.prototype._createSlider=function(){var a=
document.createElement("div");a.className="flickity-slider";a.style[this.originSide]=0;this.slider=a};l.prototype._filterFindCellElements=function(b){return a.filterFindElements(b,this.options.cellSelector)};l.prototype.reloadCells=function(){this.cells=this._makeCells(this.slider.children);this.positionCells();this._getWrapShiftCells();this.setGallerySize()};l.prototype._makeCells=function(a){a=this._filterFindCellElements(a);for(var b=[],c=0,g=a.length;g>c;c++){var e=new d(a[c],this);b.push(e)}return b};
l.prototype.getLastCell=function(){return this.cells[this.cells.length-1]};l.prototype.positionCells=function(){this._sizeCells(this.cells);this._positionCells(0)};l.prototype._positionCells=function(a){this.maxCellHeight=(a=a||0)?this.maxCellHeight||0:0;var b=0;0<a&&(b=this.cells[a-1],b=b.x+b.size.outerWidth);for(var d=this.cells.length,c=a;d>c;c++)a=this.cells[c],a.setPosition(b),b+=a.size.outerWidth,this.maxCellHeight=Math.max(a.size.outerHeight,this.maxCellHeight);this.slideableWidth=b;this._containCells()};
l.prototype._sizeCells=function(a){for(var b=0,c=a.length;c>b;b++)a[b].getSize()};l.prototype._init=l.prototype.reposition=function(){this.positionCells();this.positionSliderAtSelected()};l.prototype.getSize=function(){this.size=h(this.element);this.setCellAlign();this.cursorPosition=this.size.innerWidth*this.cellAlign};var v={center:{left:.5,right:.5},left:{left:0,right:1},right:{right:0,left:1}};l.prototype.setCellAlign=function(){var a=v[this.options.cellAlign];this.cellAlign=a?a[this.originSide]:
this.options.cellAlign};l.prototype.setGallerySize=function(){this.options.setGallerySize&&(this.viewport.style.height=this.maxCellHeight+"px")};l.prototype._getWrapShiftCells=function(){if(this.options.wrapAround){this._unshiftCells(this.beforeShiftCells);this._unshiftCells(this.afterShiftCells);var a=this.cursorPosition;this.beforeShiftCells=this._getGapCells(a,this.cells.length-1,-1);a=this.size.innerWidth-this.cursorPosition;this.afterShiftCells=this._getGapCells(a,0,1)}};l.prototype._getGapCells=
function(a,b,c){for(var d=[];0<a;){var g=this.cells[b];if(!g)break;d.push(g);b+=c;a-=g.size.outerWidth}return d};l.prototype._containCells=function(){if(this.options.contain&&!this.options.wrapAround&&this.cells.length)for(var a=this.options.rightToLeft?"marginLeft":"marginRight",b=this.cells[0].size[this.options.rightToLeft?"marginRight":"marginLeft"],c=this.getLastCell(),a=this.slideableWidth-c.size[a],c=a-this.size.innerWidth*(1-this.cellAlign),d=a<this.size.innerWidth,g=0,e=this.cells.length;e>
g;g++){var k=this.cells[g];k.setDefaultTarget();d?k.target=a*this.cellAlign:(k.target=Math.max(k.target,this.cursorPosition+b),k.target=Math.min(k.target,c))}};l.prototype.dispatchEvent=function(a,b,c){var d=[b].concat(c);if(this.emitEvent(a,d),k&&this.$element)b?(b=k.Event(b),b.type=a,this.$element.trigger(b,c)):this.$element.trigger(a,c)};l.prototype.select=function(b,c,d){if(this.isActive){b=parseInt(b,10);var g=this.cells.length;this.options.wrapAround&&1<g&&(0>b?this.x-=this.slideableWidth:b>=
g&&(this.x+=this.slideableWidth));(this.options.wrapAround||c)&&(b=a.modulo(b,g));this.cells[b]&&(this.selectedIndex=b,this.setSelectedCell(),d?this.positionSliderAtSelected():this.startAnimation(),this.dispatchEvent("cellSelect"))}};l.prototype.previous=function(a){this.select(this.selectedIndex-1,a)};l.prototype.next=function(a){this.select(this.selectedIndex+1,a)};l.prototype.setSelectedCell=function(){this._removeSelectedCellClass();this.selectedCell=this.cells[this.selectedIndex];this.selectedElement=
this.selectedCell.element;f.add(this.selectedElement,"is-selected")};l.prototype._removeSelectedCellClass=function(){this.selectedCell&&f.remove(this.selectedCell.element,"is-selected")};l.prototype.getCell=function(a){for(var b=0,c=this.cells.length;c>b;b++){var d=this.cells[b];if(d.element==a)return d}};l.prototype.getCells=function(b){b=a.makeArray(b);for(var c=[],d=0,g=b.length;g>d;d++){var e=this.getCell(b[d]);e&&c.push(e)}return c};l.prototype.getCellElements=function(){for(var a=[],b=0,c=this.cells.length;c>
b;b++)a.push(this.cells[b].element);return a};l.prototype.getParentCell=function(b){var c=this.getCell(b);return c?c:(b=a.getParent(b,".flickity-slider > *"),this.getCell(b))};l.prototype.getAdjacentCellElements=function(b,c){if(!b)return[this.selectedElement];c=void 0===c?this.selectedIndex:c;var d=this.cells.length;if(1+2*b>=d)return this.getCellElements();for(var g=[],e=c-b;c+b>=e;e++){var k=this.options.wrapAround?a.modulo(e,d):e;(k=this.cells[k])&&g.push(k.element)}return g};l.prototype.uiChange=
function(){this.emit("uiChange")};l.prototype.childUIPointerDown=function(a){this.emitEvent("childUIPointerDown",[a])};l.prototype.onresize=function(){this.watchCSS();this.resize()};a.debounceMethod(l,"onresize",150);l.prototype.resize=function(){this.isActive&&(this.getSize(),this.options.wrapAround&&(this.x=a.modulo(this.x,this.slideableWidth)),this.positionCells(),this._getWrapShiftCells(),this.setGallerySize(),this.positionSliderAtSelected())};var x=l.supportsConditionalCSS=function(){var a;return function(){if(void 0!==
a)return a;if(!w)return void(a=!1);var b=document.createElement("style"),c=document.createTextNode('body:after { content: "foo"; display: none; }');b.appendChild(c);document.head.appendChild(b);return a=-1!=w(document.body,":after").content.indexOf("foo"),document.head.removeChild(b),a}}();l.prototype.watchCSS=function(){var a=this.options.watchCSS;if(a){if(!x())return void this["fallbackOn"==a?"activate":"deactivate"]();-1!=w(this.element,":after").content.indexOf("flickity")?this.activate():this.deactivate()}};
l.prototype.onkeydown=function(a){!this.options.accessibility||document.activeElement&&document.activeElement!=this.element||(37==a.keyCode?(a=this.options.rightToLeft?"next":"previous",this.uiChange(),this[a]()):39==a.keyCode&&(a=this.options.rightToLeft?"previous":"next",this.uiChange(),this[a]()))};l.prototype.deactivate=function(){if(this.isActive){f.remove(this.element,"flickity-enabled");f.remove(this.element,"flickity-rtl");for(var a=0,c=this.cells.length;c>a;a++)this.cells[a].destroy();this._removeSelectedCellClass();
this.element.removeChild(this.viewport);m(this.slider.children,this.element);this.options.accessibility&&(this.element.removeAttribute("tabIndex"),b.unbind(this.element,"keydown",this));this.isActive=!1;this.emit("deactivate")}};l.prototype.destroy=function(){this.deactivate();this.isResizeBound&&b.unbind(c,"resize",this);this.emit("destroy");k&&this.$element&&k.removeData(this.element,"flickity");delete this.element.flickityGUID;delete p[this.guid]};a.extend(l.prototype,g);var C="attachEvent"in c;
return l.setUnselectable=function(a){C&&a.setAttribute("unselectable","on")},l.data=function(b){return(b=(b=a.getQueryElement(b))&&b.flickityGUID)&&p[b]},a.htmlInit(l,"flickity"),k&&k.bridget&&k.bridget("flickity",l),l.Cell=d,l});
(function(c,f){"function"==typeof define&&define.amd?define("unipointer/unipointer",["eventEmitter/EventEmitter","eventie/eventie"],function(e,b){return f(c,e,b)}):"object"==typeof exports?module.exports=f(c,require("wolfy87-eventemitter"),require("eventie")):c.Unipointer=f(c,c.EventEmitter,c.eventie)})(window,function(c,f,e){function b(){}b.prototype=new f;b.prototype.bindStartEvent=function(a){this._bindStartEvent(a,!0)};b.prototype.unbindStartEvent=function(a){this._bindStartEvent(a,!1)};b.prototype._bindStartEvent=
function(a,b){var g=void 0===b||b?"bind":"unbind";c.navigator.pointerEnabled?e[g](a,"pointerdown",this):c.navigator.msPointerEnabled?e[g](a,"MSPointerDown",this):(e[g](a,"mousedown",this),e[g](a,"touchstart",this))};b.prototype.handleEvent=function(a){var b="on"+a.type;this[b]&&this[b](a)};b.prototype.getTouch=function(a){for(var b=0,c=a.length;c>b;b++){var e=a[b];if(e.identifier==this.pointerIdentifier)return e}};b.prototype.onmousedown=function(a){var b=a.button;b&&0!==b&&1!==b||this._pointerDown(a,
a)};b.prototype.ontouchstart=function(a){this._pointerDown(a,a.changedTouches[0])};b.prototype.onMSPointerDown=b.prototype.onpointerdown=function(a){this._pointerDown(a,a)};b.prototype._pointerDown=function(a,b){this.isPointerDown||(this.isPointerDown=!0,this.pointerIdentifier=void 0!==b.pointerId?b.pointerId:b.identifier,this.pointerDown(a,b))};b.prototype.pointerDown=function(a,b){this._bindPostStartEvents(a);this.emitEvent("pointerDown",[a,b])};var h={mousedown:["mousemove","mouseup"],touchstart:["touchmove",
"touchend","touchcancel"],pointerdown:["pointermove","pointerup","pointercancel"],MSPointerDown:["MSPointerMove","MSPointerUp","MSPointerCancel"]};return b.prototype._bindPostStartEvents=function(a){if(a){var b=h[a.type];a=a.preventDefault?c:document;for(var g=0,f=b.length;f>g;g++)e.bind(a,b[g],this);this._boundPointerEvents={events:b,node:a}}},b.prototype._unbindPostStartEvents=function(){var a=this._boundPointerEvents;if(a&&a.events){for(var b=0,c=a.events.length;c>b;b++)e.unbind(a.node,a.events[b],
this);delete this._boundPointerEvents}},b.prototype.onmousemove=function(a){this._pointerMove(a,a)},b.prototype.onMSPointerMove=b.prototype.onpointermove=function(a){a.pointerId==this.pointerIdentifier&&this._pointerMove(a,a)},b.prototype.ontouchmove=function(a){var b=this.getTouch(a.changedTouches);b&&this._pointerMove(a,b)},b.prototype._pointerMove=function(a,b){this.pointerMove(a,b)},b.prototype.pointerMove=function(a,b){this.emitEvent("pointerMove",[a,b])},b.prototype.onmouseup=function(a){this._pointerUp(a,
a)},b.prototype.onMSPointerUp=b.prototype.onpointerup=function(a){a.pointerId==this.pointerIdentifier&&this._pointerUp(a,a)},b.prototype.ontouchend=function(a){var b=this.getTouch(a.changedTouches);b&&this._pointerUp(a,b)},b.prototype._pointerUp=function(a,b){this._pointerDone();this.pointerUp(a,b)},b.prototype.pointerUp=function(a,b){this.emitEvent("pointerUp",[a,b])},b.prototype._pointerDone=function(){this.isPointerDown=!1;delete this.pointerIdentifier;this._unbindPostStartEvents();this.pointerDone()},
b.prototype.pointerDone=function(){},b.prototype.onMSPointerCancel=b.prototype.onpointercancel=function(a){a.pointerId==this.pointerIdentifier&&this._pointerCancel(a,a)},b.prototype.ontouchcancel=function(a){var b=this.getTouch(a.changedTouches);b&&this._pointerCancel(a,b)},b.prototype._pointerCancel=function(a,b){this._pointerDone();this.pointerCancel(a,b)},b.prototype.pointerCancel=function(a,b){this.emitEvent("pointerCancel",[a,b])},b.getPointerPoint=function(a){return{x:void 0!==a.pageX?a.pageX:
a.clientX,y:void 0!==a.pageY?a.pageY:a.clientY}},b});
(function(c,f){"function"==typeof define&&define.amd?define("unidragger/unidragger",["eventie/eventie","unipointer/unipointer"],function(e,b){return f(c,e,b)}):"object"==typeof exports?module.exports=f(c,require("eventie"),require("unipointer")):c.Unidragger=f(c,c.eventie,c.Unipointer)})(window,function(c,f,e){function b(){}function h(a){a.preventDefault?a.preventDefault():a.returnValue=!1}function a(){}function d(){return!1}a.prototype=new e;a.prototype.bindHandles=function(){this._bindHandles(!0)};
a.prototype.unbindHandles=function(){this._bindHandles(!1)};var g=c.navigator;a.prototype._bindHandles=function(a){a=void 0===a||!!a;var b;b=g.pointerEnabled?function(b){b.style.touchAction=a?"none":""}:g.msPointerEnabled?function(b){b.style.msTouchAction=a?"none":""}:function(){a&&m(h)};for(var c=a?"bind":"unbind",d=0,e=this.handles.length;e>d;d++){var h=this.handles[d];this._bindStartEvent(h,a);b(h);f[c](h,"click",this)}};var m="attachEvent"in document.documentElement?function(a){"IMG"==a.nodeName&&
(a.ondragstart=d);a=a.querySelectorAll("img");for(var b=0,c=a.length;c>b;b++)a[b].ondragstart=d}:b;a.prototype.pointerDown=function(b,d){if("INPUT"==b.target.nodeName&&"range"==b.target.type)return this.isPointerDown=!1,void delete this.pointerIdentifier;this._dragPointerDown(b,d);var g=document.activeElement;g&&g.blur&&g.blur();this._bindPostStartEvents(b);this.pointerDownScroll=a.getScrollPosition();f.bind(c,"scroll",this);this.emitEvent("pointerDown",[b,d])};a.prototype._dragPointerDown=function(a,
b){this.pointerDownPoint=e.getPointerPoint(b);var c=a.target.nodeName;"touchstart"==a.type||"SELECT"==c||h(a)};a.prototype.pointerMove=function(a,b){var c=this._dragPointerMove(a,b);this.emitEvent("pointerMove",[a,b,c]);this._dragMove(a,b,c)};a.prototype._dragPointerMove=function(a,b){var c=e.getPointerPoint(b),c={x:c.x-this.pointerDownPoint.x,y:c.y-this.pointerDownPoint.y};return!this.isDragging&&this.hasDragStarted(c)&&this._dragStart(a,b),c};a.prototype.hasDragStarted=function(a){return 3<Math.abs(a.x)||
3<Math.abs(a.y)};a.prototype.pointerUp=function(a,b){this.emitEvent("pointerUp",[a,b]);this._dragPointerUp(a,b)};a.prototype._dragPointerUp=function(a,b){this.isDragging?this._dragEnd(a,b):this._staticClick(a,b)};a.prototype.pointerDone=function(){f.unbind(c,"scroll",this)};a.prototype._dragStart=function(b,c){this.isDragging=!0;this.dragStartPoint=a.getPointerPoint(c);this.isPreventingClicks=!0;this.dragStart(b,c)};a.prototype.dragStart=function(a,b){this.emitEvent("dragStart",[a,b])};a.prototype._dragMove=
function(a,b,c){this.isDragging&&this.dragMove(a,b,c)};a.prototype.dragMove=function(a,b,c){h(a);this.emitEvent("dragMove",[a,b,c])};a.prototype._dragEnd=function(a,b){this.isDragging=!1;var c=this;setTimeout(function(){delete c.isPreventingClicks});this.dragEnd(a,b)};a.prototype.dragEnd=function(a,b){this.emitEvent("dragEnd",[a,b])};a.prototype.pointerDone=function(){f.unbind(c,"scroll",this);delete this.pointerDownScroll};a.prototype.onclick=function(a){this.isPreventingClicks&&h(a)};a.prototype._staticClick=
function(a,b){if(!this.isIgnoringMouseUp||"mouseup"!=a.type){var c=a.target.nodeName;if(("INPUT"==c||"TEXTAREA"==c)&&a.target.focus(),this.staticClick(a,b),"mouseup"!=a.type){this.isIgnoringMouseUp=!0;var d=this;setTimeout(function(){delete d.isIgnoringMouseUp},400)}}};a.prototype.staticClick=function(a,b){this.emitEvent("staticClick",[a,b])};a.prototype.onscroll=function(){var b=a.getScrollPosition(),c=this.pointerDownScroll.y-b.y;(3<Math.abs(this.pointerDownScroll.x-b.x)||3<Math.abs(c))&&this._pointerDone()};
a.getPointerPoint=function(a){return{x:void 0!==a.pageX?a.pageX:a.clientX,y:void 0!==a.pageY?a.pageY:a.clientY}};var l=void 0!==c.pageYOffset;return a.getScrollPosition=function(){return{x:l?c.pageXOffset:document.body.scrollLeft,y:l?c.pageYOffset:document.body.scrollTop}},a.getPointerPoint=e.getPointerPoint,a});
(function(c,f){"function"==typeof define&&define.amd?define("flickity/js/drag",["classie/classie","eventie/eventie","./flickity","unidragger/unidragger","fizzy-ui-utils/utils"],function(e,b,h,a,d){return f(c,e,b,h,a,d)}):"object"==typeof exports?module.exports=f(c,require("desandro-classie"),require("eventie"),require("./flickity"),require("unidragger"),require("fizzy-ui-utils")):c.Flickity=f(c,c.classie,c.eventie,c.Flickity,c.Unidragger,c.fizzyUIUtils)})(window,function(c,f,e,b,h,a){a.extend(b.defaults,
{draggable:!0});b.createMethods.push("_createDrag");a.extend(b.prototype,h.prototype);b.prototype._createDrag=function(){this.on("activate",this.bindDrag);this.on("uiChange",this._uiChangeDrag);this.on("childUIPointerDown",this._childUIPointerDownDrag);this.on("deactivate",this.unbindDrag)};b.prototype.bindDrag=function(){this.options.draggable&&!this.isDragBound&&(f.add(this.element,"is-draggable"),this.handles=[this.viewport],this.bindHandles(),this.isDragBound=!0)};b.prototype.unbindDrag=function(){this.isDragBound&&
(f.remove(this.element,"is-draggable"),this.unbindHandles(),delete this.isDragBound)};b.prototype._uiChangeDrag=function(){delete this.isFreeScrolling};b.prototype._childUIPointerDownDrag=function(a){a.preventDefault?a.preventDefault():a.returnValue=!1;this.pointerDownFocus(a)};b.prototype.pointerDown=function(a,b){if("INPUT"==a.target.nodeName&&"range"==a.target.type)return this.isPointerDown=!1,void delete this.pointerIdentifier;this._dragPointerDown(a,b);var d=document.activeElement;d&&d.blur&&
d!=this.element&&d!=document.body&&d.blur();this.pointerDownFocus(a);this.dragX=this.x;f.add(this.viewport,"is-pointer-down");this._bindPostStartEvents(a);this.pointerDownScroll=h.getScrollPosition();e.bind(c,"scroll",this);this.dispatchEvent("pointerDown",a,[b])};var d={touchstart:!0,MSPointerDown:!0},g={INPUT:!0,SELECT:!0};return b.prototype.pointerDownFocus=function(a){!this.options.accessibility||d[a.type]||g[a.target.nodeName]||(a=c.pageYOffset,this.element.focus(),c.pageYOffset!=a&&c.scrollTo(c.pageXOffset,
a))},b.prototype.hasDragStarted=function(a){return 3<Math.abs(a.x)},b.prototype.pointerUp=function(a,b){f.remove(this.viewport,"is-pointer-down");this.dispatchEvent("pointerUp",a,[b]);this._dragPointerUp(a,b)},b.prototype.pointerDone=function(){e.unbind(c,"scroll",this);delete this.pointerDownScroll},b.prototype.dragStart=function(a,b){this.dragStartPosition=this.x;this.startAnimation();this.dispatchEvent("dragStart",a,[b])},b.prototype.dragMove=function(a,b,c){a.preventDefault?a.preventDefault():
a.returnValue=!1;this.previousDragX=this.dragX;var d=this.dragStartPosition+c.x*(this.options.rightToLeft?-1:1);if(!this.options.wrapAround&&this.cells.length)var g=Math.max(-this.cells[0].target,this.dragStartPosition),d=d>g?.5*(d+g):d,g=Math.min(-this.getLastCell().target,this.dragStartPosition),d=g>d?.5*(d+g):d;this.dragX=d;this.dragMoveTime=new Date;this.dispatchEvent("dragMove",a,[b,c])},b.prototype.dragEnd=function(a,b){this.options.freeScroll&&(this.isFreeScrolling=!0);var c=this.dragEndRestingSelect();
if(this.options.freeScroll&&!this.options.wrapAround){var d=this.getRestingPosition();this.isFreeScrolling=-d>this.cells[0].target&&-d<this.getLastCell().target}else this.options.freeScroll||c!=this.selectedIndex||(c+=this.dragEndBoostSelect());delete this.previousDragX;this.select(c);this.dispatchEvent("dragEnd",a,[b])},b.prototype.dragEndRestingSelect=function(){var a=this.getRestingPosition(),b=Math.abs(this.getCellDistance(-a,this.selectedIndex)),c=this._getClosestResting(a,b,1),a=this._getClosestResting(a,
b,-1);return c.distance<a.distance?c.index:a.index},b.prototype._getClosestResting=function(a,b,c){for(var d=this.selectedIndex,g=1/0,e=this.options.contain&&!this.options.wrapAround?function(a,b){return b>=a}:function(a,b){return b>a};e(b,g)&&(d+=c,g=b,b=this.getCellDistance(-a,d),null!==b);)b=Math.abs(b);return{distance:g,index:d-c}},b.prototype.getCellDistance=function(b,c){var d=this.cells.length,g=this.options.wrapAround&&1<d,e=g?a.modulo(c,d):c;return(e=this.cells[e])?b-(e.target+(g?this.slideableWidth*
Math.floor(c/d):0)):null},b.prototype.dragEndBoostSelect=function(){if(void 0===this.previousDragX||!this.dragMoveTime||100<new Date-this.dragMoveTime)return 0;var a=this.getCellDistance(-this.dragX,this.selectedIndex),b=this.previousDragX-this.dragX;return 0<a&&0<b?1:0>a&&0>b?-1:0},b.prototype.staticClick=function(b,c){var d=this.getParentCell(b.target),g=d&&d.element,d=d&&a.indexOf(this.cells,d);this.dispatchEvent("staticClick",b,[c,g,d])},b});
(function(c,f){"function"==typeof define&&define.amd?define("tap-listener/tap-listener",["unipointer/unipointer"],function(e){return f(c,e)}):"object"==typeof exports?module.exports=f(c,require("unipointer")):c.TapListener=f(c,c.Unipointer)})(window,function(c,f){function e(b){this.bindTap(b)}e.prototype=new f;e.prototype.bindTap=function(b){b&&(this.unbindTap(),this.tapElement=b,this._bindStartEvent(b,!0))};e.prototype.unbindTap=function(){this.tapElement&&(this._bindStartEvent(this.tapElement,!0),
delete this.tapElement)};var b=void 0!==c.pageYOffset;return e.prototype.pointerUp=function(e,a){if(!this.isIgnoringMouseUp||"mouseup"!=e.type){var d=f.getPointerPoint(a),g=this.tapElement.getBoundingClientRect(),m=b?c.pageXOffset:document.body.scrollLeft,l=b?c.pageYOffset:document.body.scrollTop;d.x>=g.left+m&&d.x<=g.right+m&&d.y>=g.top+l&&d.y<=g.bottom+l&&this.emitEvent("tap",[e,a]);"mouseup"!=e.type&&(this.isIgnoringMouseUp=!0,setTimeout(function(){delete this.isIgnoringMouseUp}.bind(this),320))}},
e.prototype.destroy=function(){this.pointerDone();this.unbindTap()},e});
(function(c,f){"function"==typeof define&&define.amd?define("flickity/js/prev-next-button",["eventie/eventie","./flickity","tap-listener/tap-listener","fizzy-ui-utils/utils"],function(e,b,h,a){return f(c,e,b,h,a)}):"object"==typeof exports?module.exports=f(c,require("eventie"),require("./flickity"),require("tap-listener"),require("fizzy-ui-utils")):f(c,c.eventie,c.Flickity,c.TapListener,c.fizzyUIUtils)})(window,function(c,f,e,b,h){function a(a,b){this.direction=a;this.parent=b;this._create()}var d=
function(){var a;return function(){if(void 0!==a)return a;var b=document.createElement("div");return b.innerHTML="<svg/>",a="http://www.w3.org/2000/svg"==(b.firstChild&&b.firstChild.namespaceURI)}}();return a.prototype=new b,a.prototype._create=function(){this.isEnabled=!0;this.isPrevious=-1==this.direction;this.isLeft=this.direction==(this.parent.options.rightToLeft?1:-1);var a=this.element=document.createElement("button");if(a.className="flickity-prev-next-button",a.className+=this.isPrevious?" previous":
" next",a.setAttribute("type","button"),this.disable(),a.setAttribute("aria-label",this.isPrevious?"previous":"next"),e.setUnselectable(a),d()){var b=this.createSVG();a.appendChild(b)}else this.setArrowText(),a.className+=" no-svg";var c=this;this.onCellSelect=function(){c.update()};this.parent.on("cellSelect",this.onCellSelect);this.on("tap",this.onTap);this.on("pointerDown",function(a,b){c.parent.childUIPointerDown(b)})},a.prototype.activate=function(){this.bindTap(this.element);f.bind(this.element,
"click",this);this.parent.element.appendChild(this.element)},a.prototype.deactivate=function(){this.parent.element.removeChild(this.element);b.prototype.destroy.call(this);f.unbind(this.element,"click",this)},a.prototype.createSVG=function(){var a=document.createElementNS("http://www.w3.org/2000/svg","svg");a.setAttribute("viewBox","0 0 100 100");var b=document.createElementNS("http://www.w3.org/2000/svg","path"),c=this.parent.options.arrowShape;return b.setAttribute("d","string"==typeof c?c:"M "+
c.x0+",50 L "+c.x1+","+(c.y1+50)+" L "+c.x2+","+(c.y2+50)+" L "+c.x3+",50  L "+c.x2+","+(50-c.y2)+" L "+c.x1+","+(50-c.y1)+" Z"),b.setAttribute("class","arrow"),this.isLeft||b.setAttribute("transform","translate(100, 100) rotate(180) "),a.appendChild(b),a},a.prototype.setArrowText=function(){var a=this.parent.options;h.setText(this.element,this.isLeft?a.leftArrowText:a.rightArrowText)},a.prototype.onTap=function(){this.isEnabled&&(this.parent.uiChange(),this.parent[this.isPrevious?"previous":"next"]())},
a.prototype.handleEvent=h.handleEvent,a.prototype.onclick=function(){var a=document.activeElement;a&&a==this.element&&this.onTap()},a.prototype.enable=function(){this.isEnabled||(this.element.disabled=!1,this.isEnabled=!0)},a.prototype.disable=function(){this.isEnabled&&(this.element.disabled=!0,this.isEnabled=!1)},a.prototype.update=function(){var a=this.parent.cells;if(this.parent.options.wrapAround&&1<a.length)return void this.enable();a=a.length?a.length-1:0;this[this.parent.selectedIndex==(this.isPrevious?
0:a)?"disable":"enable"]()},a.prototype.destroy=function(){this.deactivate()},h.extend(e.defaults,{prevNextButtons:!0,leftArrowText:"\u00e2\u20ac\u00b9",rightArrowText:"\u00e2\u20ac\u00ba",arrowShape:{x0:10,x1:60,y1:50,x2:70,y2:40,x3:30}}),e.createMethods.push("_createPrevNextButtons"),e.prototype._createPrevNextButtons=function(){this.options.prevNextButtons&&(this.prevButton=new a(-1,this),this.nextButton=new a(1,this),this.on("activate",this.activatePrevNextButtons))},e.prototype.activatePrevNextButtons=
function(){this.prevButton.activate();this.nextButton.activate();this.on("deactivate",this.deactivatePrevNextButtons)},e.prototype.deactivatePrevNextButtons=function(){this.prevButton.deactivate();this.nextButton.deactivate();this.off("deactivate",this.deactivatePrevNextButtons)},e.PrevNextButton=a,e});
(function(c,f){"function"==typeof define&&define.amd?define("flickity/js/page-dots",["eventie/eventie","./flickity","tap-listener/tap-listener","fizzy-ui-utils/utils"],function(e,b,h,a){return f(c,e,b,h,a)}):"object"==typeof exports?module.exports=f(c,require("eventie"),require("./flickity"),require("tap-listener"),require("fizzy-ui-utils")):f(c,c.eventie,c.Flickity,c.TapListener,c.fizzyUIUtils)})(window,function(c,f,e,b,h){function a(a){this.parent=a;this._create()}return a.prototype=new b,a.prototype._create=
function(){this.holder=document.createElement("ol");this.holder.className="flickity-page-dots";e.setUnselectable(this.holder);this.dots=[];var a=this;this.onCellSelect=function(){a.updateSelected()};this.parent.on("cellSelect",this.onCellSelect);this.on("tap",this.onTap);this.on("pointerDown",function(b,c){a.parent.childUIPointerDown(c)})},a.prototype.activate=function(){this.setDots();this.bindTap(this.holder);this.parent.element.appendChild(this.holder)},a.prototype.deactivate=function(){this.parent.element.removeChild(this.holder);
b.prototype.destroy.call(this)},a.prototype.setDots=function(){var a=this.parent.cells.length-this.dots.length;0<a?this.addDots(a):0>a&&this.removeDots(-a)},a.prototype.addDots=function(a){for(var b=document.createDocumentFragment(),c=[];a;){var e=document.createElement("li");e.className="dot";b.appendChild(e);c.push(e);a--}this.holder.appendChild(b);this.dots=this.dots.concat(c)},a.prototype.removeDots=function(a){a=this.dots.splice(this.dots.length-a,a);for(var b=0,c=a.length;c>b;b++)this.holder.removeChild(a[b])},
a.prototype.updateSelected=function(){this.selectedDot&&(this.selectedDot.className="dot");this.dots.length&&(this.selectedDot=this.dots[this.parent.selectedIndex],this.selectedDot.className="dot is-selected")},a.prototype.onTap=function(a){a=a.target;"LI"==a.nodeName&&(this.parent.uiChange(),a=h.indexOf(this.dots,a),this.parent.select(a))},a.prototype.destroy=function(){this.deactivate()},e.PageDots=a,h.extend(e.defaults,{pageDots:!0}),e.createMethods.push("_createPageDots"),e.prototype._createPageDots=
function(){this.options.pageDots&&(this.pageDots=new a(this),this.on("activate",this.activatePageDots),this.on("cellAddedRemoved",this.onCellAddedRemovedPageDots),this.on("deactivate",this.deactivatePageDots))},e.prototype.activatePageDots=function(){this.pageDots.activate()},e.prototype.onCellAddedRemovedPageDots=function(){this.pageDots.setDots()},e.prototype.deactivatePageDots=function(){this.pageDots.deactivate()},e.PageDots=a,e});
(function(c,f){"function"==typeof define&&define.amd?define("flickity/js/player",["eventEmitter/EventEmitter","eventie/eventie","fizzy-ui-utils/utils","./flickity"],function(c,b,h,a){return f(c,b,h,a)}):"object"==typeof exports?module.exports=f(require("wolfy87-eventemitter"),require("eventie"),require("fizzy-ui-utils"),require("./flickity")):f(c.EventEmitter,c.eventie,c.fizzyUIUtils,c.Flickity)})(window,function(c,f,e,b){function h(a){if(this.parent=a,this.state="stopped",d){var b=this;this.onVisibilityChange=
function(){b.visibilityChange()}}}var a,d;return"hidden"in document?(a="hidden",d="visibilitychange"):"webkitHidden"in document&&(a="webkitHidden",d="webkitvisibilitychange"),h.prototype=new c,h.prototype.play=function(){"playing"!=this.state&&(this.state="playing",d&&document.addEventListener(d,this.onVisibilityChange,!1),this.tick())},h.prototype.tick=function(){if("playing"==this.state){var a=this.parent.options.autoPlay,a="number"==typeof a?a:3E3,b=this;this.clear();this.timeout=setTimeout(function(){b.parent.next(!0);
b.tick()},a)}},h.prototype.stop=function(){this.state="stopped";this.clear();d&&document.removeEventListener(d,this.onVisibilityChange,!1)},h.prototype.clear=function(){clearTimeout(this.timeout)},h.prototype.pause=function(){"playing"==this.state&&(this.state="paused",this.clear())},h.prototype.unpause=function(){"paused"==this.state&&this.play()},h.prototype.visibilityChange=function(){this[document[a]?"pause":"unpause"]()},e.extend(b.defaults,{pauseAutoPlayOnHover:!0}),b.createMethods.push("_createPlayer"),
b.prototype._createPlayer=function(){this.player=new h(this);this.on("activate",this.activatePlayer);this.on("uiChange",this.stopPlayer);this.on("pointerDown",this.stopPlayer);this.on("deactivate",this.deactivatePlayer)},b.prototype.activatePlayer=function(){this.options.autoPlay&&(this.player.play(),f.bind(this.element,"mouseenter",this),this.isMouseenterBound=!0)},b.prototype.playPlayer=function(){this.player.play()},b.prototype.stopPlayer=function(){this.player.stop()},b.prototype.pausePlayer=
function(){this.player.pause()},b.prototype.unpausePlayer=function(){this.player.unpause()},b.prototype.deactivatePlayer=function(){this.player.stop();this.isMouseenterBound&&(f.unbind(this.element,"mouseenter",this),delete this.isMouseenterBound)},b.prototype.onmouseenter=function(){this.options.pauseAutoPlayOnHover&&(this.player.pause(),f.bind(this.element,"mouseleave",this))},b.prototype.onmouseleave=function(){this.player.unpause();f.unbind(this.element,"mouseleave",this)},b.Player=h,b});
(function(c,f){"function"==typeof define&&define.amd?define("flickity/js/add-remove-cell",["./flickity","fizzy-ui-utils/utils"],function(e,b){return f(c,e,b)}):"object"==typeof exports?module.exports=f(c,require("./flickity"),require("fizzy-ui-utils")):f(c,c.Flickity,c.fizzyUIUtils)})(window,function(c,f,e){return f.prototype.insert=function(b,c){var a=this._makeCells(b);if(a&&a.length){var d=this.cells.length;c=void 0===c?d:c;for(var e=document.createDocumentFragment(),f=0,l=a.length;l>f;f++)e.appendChild(a[f].element);
(f=c==d)?this.slider.appendChild(e):this.slider.insertBefore(e,this.cells[c].element);0===c?this.cells=a.concat(this.cells):f?this.cells=this.cells.concat(a):(d=this.cells.splice(c,d-c),this.cells=this.cells.concat(a).concat(d));this._sizeCells(a);this._cellAddedRemoved(c,c>this.selectedIndex?0:a.length)}},f.prototype.append=function(b){this.insert(b,this.cells.length)},f.prototype.prepend=function(b){this.insert(b,0)},f.prototype.remove=function(b){var c,a,d=this.getCells(b),g=0;b=0;for(c=d.length;c>
b;b++)a=d[b],a=e.indexOf(this.cells,a)<this.selectedIndex,g-=a?1:0;b=0;for(c=d.length;c>b;b++)a=d[b],a.remove(),e.removeFrom(this.cells,a);d.length&&this._cellAddedRemoved(0,g)},f.prototype._cellAddedRemoved=function(b,c){c=c||0;this.selectedIndex+=c;this.selectedIndex=Math.max(0,Math.min(this.cells.length-1,this.selectedIndex));this.emitEvent("cellAddedRemoved",[b,c]);this.cellChange(b,!0)},f.prototype.cellSizeChange=function(b){if(b=this.getCell(b))b.getSize(),b=e.indexOf(this.cells,b),this.cellChange(b)},
f.prototype.cellChange=function(b,c){var a=this.slideableWidth;(this._positionCells(b),this._getWrapShiftCells(),this.setGallerySize(),this.options.freeScroll)?(this.x+=(a-this.slideableWidth)*this.cellAlign,this.positionSlider()):(c&&this.positionSliderAtSelected(),this.select(this.selectedIndex))},f});
(function(c,f){"function"==typeof define&&define.amd?define("flickity/js/lazyload",["classie/classie","eventie/eventie","./flickity","fizzy-ui-utils/utils"],function(e,b,h,a){return f(c,e,b,h,a)}):"object"==typeof exports?module.exports=f(c,require("desandro-classie"),require("eventie"),require("./flickity"),require("fizzy-ui-utils")):f(c,c.classie,c.eventie,c.Flickity,c.fizzyUIUtils)})(window,function(c,f,e,b,h){function a(a,b){this.img=a;this.flickity=b;this.load()}return b.createMethods.push("_createLazyload"),
b.prototype._createLazyload=function(){this.on("cellSelect",this.lazyLoad)},b.prototype.lazyLoad=function(){var b=this.options.lazyLoad;if(b){for(var b=this.getAdjacentCellElements("number"==typeof b?b:0),c=[],e=0,f=b.length;f>e;e++){var k;k=b[e];"IMG"==k.nodeName&&k.getAttribute("data-flickity-lazyload")?k=[k]:(k=k.querySelectorAll("img[data-flickity-lazyload]"),k=h.makeArray(k));c=c.concat(k)}e=0;for(f=c.length;f>e;e++)new a(c[e],this)}},a.prototype.handleEvent=h.handleEvent,a.prototype.load=function(){e.bind(this.img,
"load",this);e.bind(this.img,"error",this);this.img.src=this.img.getAttribute("data-flickity-lazyload");this.img.removeAttribute("data-flickity-lazyload")},a.prototype.onload=function(a){this.complete(a,"flickity-lazyloaded")},a.prototype.onerror=function(a){this.complete(a,"flickity-lazyerror")},a.prototype.complete=function(a,b){e.unbind(this.img,"load",this);e.unbind(this.img,"error",this);var c=this.flickity.getParentCell(this.img),c=c&&c.element;this.flickity.cellSizeChange(c);f.add(this.img,
b);this.flickity.dispatchEvent("lazyLoad",a,c)},b.LazyLoader=a,b});(function(c,f){"function"==typeof define&&define.amd?define("flickity/js/index","./flickity ./drag ./prev-next-button ./page-dots ./player ./add-remove-cell ./lazyload".split(" "),f):"object"==typeof exports&&(module.exports=f(require("./flickity"),require("./drag"),require("./prev-next-button"),require("./page-dots"),require("./player"),require("./add-remove-cell"),require("./lazyload")))})(window,function(c){return c});
(function(c,f){"function"==typeof define&&define.amd?define("flickity-as-nav-for/as-nav-for",["classie/classie","flickity/js/index","fizzy-ui-utils/utils"],function(e,b,h){return f(c,e,b,h)}):"object"==typeof exports?module.exports=f(c,require("desandro-classie"),require("flickity"),require("fizzy-ui-utils")):c.Flickity=f(c,c.classie,c.Flickity,c.fizzyUIUtils)})(window,function(c,f,e,b){return e.createMethods.push("_createAsNavFor"),e.prototype._createAsNavFor=function(){this.on("activate",this.activateAsNavFor);
this.on("deactivate",this.deactivateAsNavFor);this.on("destroy",this.destroyAsNavFor);var b=this.options.asNavFor;if(b){var a=this;setTimeout(function(){a.setNavCompanion(b)})}},e.prototype.setNavCompanion=function(c){c=b.getQueryElement(c);if((c=e.data(c))&&c!=this){this.navCompanion=c;var a=this;this.onNavCompanionSelect=function(){a.navCompanionSelect()};c.on("cellSelect",this.onNavCompanionSelect);this.on("staticClick",this.onNavStaticClick);this.navCompanionSelect()}},e.prototype.navCompanionSelect=
function(){if(this.navCompanion){var b=this.navCompanion.selectedIndex;this.select(b);this.removeNavSelectedElement();this.selectedIndex==b&&(this.navSelectedElement=this.cells[b].element,f.add(this.navSelectedElement,"is-nav-selected"))}},e.prototype.activateAsNavFor=function(){this.navCompanionSelect()},e.prototype.removeNavSelectedElement=function(){this.navSelectedElement&&(f.remove(this.navSelectedElement,"is-nav-selected"),delete this.navSelectedElement)},e.prototype.onNavStaticClick=function(b,
a,c,e){"number"==typeof e&&this.navCompanion.select(e)},e.prototype.deactivateAsNavFor=function(){this.removeNavSelectedElement()},e.prototype.destroyAsNavFor=function(){this.navCompanion&&(this.navCompanion.off("cellSelect",this.onNavCompanionSelect),this.off("staticClick",this.onNavStaticClick),delete this.navCompanion)},e});
(function(c,f){"function"==typeof define&&define.amd?define("imagesloaded/imagesloaded",["eventEmitter/EventEmitter","eventie/eventie"],function(e,b){return f(c,e,b)}):"object"==typeof module&&module.exports?module.exports=f(c,require("wolfy87-eventemitter"),require("eventie")):c.imagesLoaded=f(c,c.EventEmitter,c.eventie)})(window,function(c,f,e){function b(a,b){for(var c in b)a[c]=b[c];return a}function h(a){var b=[];if("[object Array]"==k.call(a))b=a;else if("number"==typeof a.length)for(var c=
0;c<a.length;c++)b.push(a[c]);else b.push(a);return b}function a(c,d,e){if(!(this instanceof a))return new a(c,d,e);"string"==typeof c&&(c=document.querySelectorAll(c));this.elements=h(c);this.options=b({},this.options);"function"==typeof d?e=d:b(this.options,d);e&&this.on("always",e);this.getImages();m&&(this.jqDeferred=new m.Deferred);var g=this;setTimeout(function(){g.check()})}function d(a){this.img=a}function g(a,b){this.url=a;this.element=b;this.img=new Image}var m=c.jQuery,l=c.console,k=Object.prototype.toString;
a.prototype=new f;a.prototype.options={};a.prototype.getImages=function(){this.images=[];for(var a=0;a<this.elements.length;a++)this.addElementImages(this.elements[a])};a.prototype.addElementImages=function(a){"IMG"==a.nodeName&&this.addImage(a);!0===this.options.background&&this.addElementBackgroundImages(a);var b=a.nodeType;if(b&&w[b]){for(var c=a.querySelectorAll("img"),b=0;b<c.length;b++)this.addImage(c[b]);if("string"==typeof this.options.background)for(a=a.querySelectorAll(this.options.background),
b=0;b<a.length;b++)this.addElementBackgroundImages(a[b])}};var w={1:!0,9:!0,11:!0};a.prototype.addElementBackgroundImages=function(a){for(var b=n(a),c=/url\(['"]*([^'"\)]+)['"]*\)/gi,d=c.exec(b.backgroundImage);null!==d;)(d=d&&d[1])&&this.addBackground(d,a),d=c.exec(b.backgroundImage)};var n=c.getComputedStyle||function(a){return a.currentStyle};return a.prototype.addImage=function(a){a=new d(a);this.images.push(a)},a.prototype.addBackground=function(a,b){var c=new g(a,b);this.images.push(c)},a.prototype.check=
function(){function a(c,d,e){setTimeout(function(){b.progress(c,d,e)})}var b=this;if(this.progressedCount=0,this.hasAnyBroken=!1,!this.images.length)return void this.complete();for(var c=0;c<this.images.length;c++){var d=this.images[c];d.once("progress",a);d.check()}},a.prototype.progress=function(a,b,c){this.progressedCount++;this.hasAnyBroken=this.hasAnyBroken||!a.isLoaded;this.emit("progress",this,a,b);this.jqDeferred&&this.jqDeferred.notify&&this.jqDeferred.notify(this,a);this.progressedCount==
this.images.length&&this.complete();this.options.debug&&l&&l.log("progress: "+c,a,b)},a.prototype.complete=function(){var a=this.hasAnyBroken?"fail":"done";if(this.isComplete=!0,this.emit(a,this),this.emit("always",this),this.jqDeferred)this.jqDeferred[this.hasAnyBroken?"reject":"resolve"](this)},d.prototype=new f,d.prototype.check=function(){return this.getIsImageComplete()?void this.confirm(0!==this.img.naturalWidth,"naturalWidth"):(this.proxyImage=new Image,e.bind(this.proxyImage,"load",this),
e.bind(this.proxyImage,"error",this),e.bind(this.img,"load",this),e.bind(this.img,"error",this),void(this.proxyImage.src=this.img.src))},d.prototype.getIsImageComplete=function(){return this.img.complete&&void 0!==this.img.naturalWidth},d.prototype.confirm=function(a,b){this.isLoaded=a;this.emit("progress",this,this.img,b)},d.prototype.handleEvent=function(a){var b="on"+a.type;this[b]&&this[b](a)},d.prototype.onload=function(){this.confirm(!0,"onload");this.unbindEvents()},d.prototype.onerror=function(){this.confirm(!1,
"onerror");this.unbindEvents()},d.prototype.unbindEvents=function(){e.unbind(this.proxyImage,"load",this);e.unbind(this.proxyImage,"error",this);e.unbind(this.img,"load",this);e.unbind(this.img,"error",this)},g.prototype=new d,g.prototype.check=function(){e.bind(this.img,"load",this);e.bind(this.img,"error",this);this.img.src=this.url;this.getIsImageComplete()&&(this.confirm(0!==this.img.naturalWidth,"naturalWidth"),this.unbindEvents())},g.prototype.unbindEvents=function(){e.unbind(this.img,"load",
this);e.unbind(this.img,"error",this)},g.prototype.confirm=function(a,b){this.isLoaded=a;this.emit("progress",this,this.element,b)},a.makeJQueryPlugin=function(b){(b=b||c.jQuery)&&(m=b,m.fn.imagesLoaded=function(b,c){return(new a(this,b,c)).jqDeferred.promise(m(this))})},a.makeJQueryPlugin(),a});
(function(c,f){"function"==typeof define&&define.amd?define(["flickity/js/index","imagesloaded/imagesloaded"],function(e,b){return f(c,e,b)}):"object"==typeof exports?module.exports=f(c,require("flickity"),require("imagesloaded")):c.Flickity=f(c,c.Flickity,c.imagesLoaded)})(window,function(c,f,e){return f.createMethods.push("_createImagesLoaded"),f.prototype._createImagesLoaded=function(){this.on("activate",this.imagesLoaded)},f.prototype.imagesLoaded=function(){function b(a,b){var e=c.getParentCell(b.img);
c.cellSizeChange(e&&e.element);c.options.freeScroll||c.positionSliderAtSelected()}if(this.options.imagesLoaded){var c=this;e(this.slider).on("progress",b)}},f});
var elem=document.querySelector(".courses-carousel"),flkty=new Flickity(elem,{contain:!0,wrapAround:!0,prevNextButtons:!1,pageDots:!1}),elem=document.querySelector(".reviews-carousel"),flkty=new Flickity(elem,{contain:!0,wrapAround:!0,prevNextButtons:!1,pageDots:!1}),elem=document.querySelector(".tweets-carousel"),flkty=new Flickity(elem,{contain:!0,wrapAround:!0,prevNextButtons:!1,pageDots:!1});
!function(){function c(){}function f(b){return a.retinaImageSuffix+b}function e(a,b){if(this.path=a||"","undefined"!=typeof b&&null!==b)this.at_2x_path=b,this.perform_check=!1;else{if(void 0!==document.createElement){var c=document.createElement("a");c.href=this.path;c.pathname=c.pathname.replace(d,f);this.at_2x_path=c.href}else c=this.path.split("?"),c[0]=c[0].replace(d,f),this.at_2x_path=c.join("?");this.perform_check=!0}}function b(a){this.el=a;this.path=new e(this.el.getAttribute("src"),this.el.getAttribute("data-at2x"));
var b=this;this.path.check_2x_variant(function(a){a&&b.swap()})}var h="undefined"==typeof exports?window:exports,a={retinaImageSuffix:"@2x",check_mime_type:!0,force_original_dimensions:!0};h.Retina=c;c.configure=function(b){null===b&&(b={});for(var c in b)b.hasOwnProperty(c)&&(a[c]=b[c])};c.init=function(a){null===a&&(a=h);var c=a.onload||function(){};a.onload=function(){var a,d,e=document.getElementsByClassName("2x"),f=[];for(a=0;a<e.length;a+=1)d=e[a],d.getAttributeNode("data-no-retina")||f.push(new b(d));
c()}};c.isRetina=function(){return 1<h.devicePixelRatio||!(!h.matchMedia||!h.matchMedia("(-webkit-min-device-pixel-ratio: 1.5), (min--moz-device-pixel-ratio: 1.5), (-o-min-device-pixel-ratio: 3/2), (min-resolution: 1.5dppx)").matches)};var d=/\.\w+$/;h.RetinaImagePath=e;e.confirmed_paths=[];e.prototype.is_external=function(){return!(!this.path.match(/^https?\:/i)||this.path.match("//"+document.domain))};e.prototype.check_2x_variant=function(b){var c,d=this;return this.is_external()?b(!1):this.perform_check||
"undefined"==typeof this.at_2x_path||null===this.at_2x_path?this.at_2x_path in e.confirmed_paths?b(!0):(c=new XMLHttpRequest,c.open("HEAD",this.at_2x_path),c.onreadystatechange=function(){if(4!==c.readyState)return b(!1);if(200<=c.status&&399>=c.status){if(a.check_mime_type){var f=c.getResponseHeader("Content-Type");if(null===f||!f.match(/^image/i))return b(!1)}return e.confirmed_paths.push(d.at_2x_path),b(!0)}return b(!1)},c.send(),void 0):b(!0)};h.RetinaImage=b;b.prototype.swap=function(b){function c(){d.el.complete?
(a.force_original_dimensions&&(d.el.setAttribute("width",d.el.offsetWidth),d.el.setAttribute("height",d.el.offsetHeight)),d.el.setAttribute("src",b)):setTimeout(c,5)}"undefined"==typeof b&&(b=this.path.at_2x_path);var d=this;c()};c.isRetina()&&c.init(h)}();
©2009 Google - Terms of Service - Privacy Policy - Google Home
